#!/bin/bash

# Picks murderer and assigns value to variables
# Person = KILLER
# Time Peroid = PLACE
function pickMurderer() {
    characters[0]="theodora"
    characters[1]="tim"
    characters[2]="robert"
    characters[3]="adam"
    characters[4]="mort"
    char_size=${#characters[@]}
    KILLER=$(($RANDOM % $char_size))

    time[0]="middle"
    time[1]="wild"
    time[2]="war"
    time[3]="madmax"
    time[4]="starwars"
    time_size=${#time[@]}
    TIME=$(($RANDOM % $time_size))
}

# Starting Hub area and other areas
function setLocations() {
# Characters
# 2 in hub, 1 in middle ages, 1 in the war, 1 in mad max
    # Hub
    HUB_CHAR1=$(($RANDOM % $char_size))
    HUB_CHAR2=$(($RANDOM % $char_size))
    while [ $HUB_CHAR2 -eq $HUB_CHAR1 ]; do
	HUB_CHAR2=$(($RANDOM % $char_size))
    done
    if [[ $HUB_CHAR1 -eq 0 ]]; then
	mv $FILELOCATION/Game/Hub/.char-theodora $FILELOCATION/Game/Hub/Theodora
    elif [[ $HUB_CHAR1 -eq 1 ]]; then
	mv $FILELOCATION/Game/Hub/.char-tim $FILELOCATION/Game/Hub/Tim
    elif [[ $HUB_CHAR1 -eq 2 ]]; then
	mv $FILELOCATION/Game/Hub/.char-robert $FILELOCATION/Game/Hub/Robert
    elif [[ $HUB_CHAR1 -eq 3 ]]; then
	mv $FILELOCATION/Game/Hub/.char-adam $FILELOCATION/Game/Hub/Adam
    else
	mv $FILELOCATION/Game/Hub/.char-mort $FILELOCATION/Game/Hub/Mort
    fi
    if [[ $HUB_CHAR2 -eq 0 ]]; then
	mv $FILELOCATION/Game/Hub/.char-theodora $FILELOCATION/Game/Hub/Theodora
    elif [[ $HUB_CHAR2 -eq 1 ]]; then
	mv $FILELOCATION/Game/Hub/.char-tim $FILELOCATION/Game/Hub/Tim
    elif [[ $HUB_CHAR2 -eq 2 ]]; then
	mv $FILELOCATION/Game/Hub/.char-robert $FILELOCATION/Game/Hub/Robert
    elif [[ $HUB_CHAR2 -eq 3 ]]; then
	mv $FILELOCATION/Game/Hub/.char-adam $FILELOCATION/Game/Hub/Adam
    else
	mv $FILELOCATION/Game/Hub/.char-mort $FILELOCATION/Game/Hub/Mort
    fi

    #Middle Ages
    MIDDLE_CHAR1=$(($RANDOM % $char_size))
    while [ $MIDDLE_CHAR1 -eq ($HUB_CHAR1 || $HUB_CHAR2) ]; do
	MIDDLE_CHAR1=$(($RANDOM % $char_size))
    done
    if [[ $MIDDLE_CHAR1 -eq 0 ]]; then
	mv $FILELOCATION/Hub/.time-middle/.char-theodora $FILELOCATION/Hub/.middle/Theodora
    elif [[ $MIDDLE_CHAR1 -eq 1 ]]; then
	mv $FILELOCATION/Hub/.time-middle/.char-tim $FILELOCATION/Hub/.middle/Tim
    elif [[ $MIDDLE_CHAR1 -eq 2 ]]; then
	mv $FILELOCATION/Hub/.time-middle/.char-robert $FILELOCATION/Hub/.middle/Robert
    elif [[ $MIDDLE_CHAR1 -eq 3 ]]; then
	mv $FILELOCATION/Hub/.time-middle/.char-adam $FILELOCATION/Hub/.middle/Adam
    else
	mv $FILELOCATION/Hub/.time-middle/.char-mort $FILELOCATION/Hub/.middle/Mort
    fi

   #The War
    WAR_CHAR1=$(($RANDOM % $char_size))
    while [ $WAR_CHAR1 -eq ($HUB_CHAR1 || $HUB_CHAR2 || $MIDDLE_CHAR1) ]; do
	WAR_CHAR1=$(($RANDOM % $char_size))
    done
    if [[ $WAR_CHAR1 -eq 0 ]]; then
	mv $FILELOCATION/Hub/.time-war/.char-theodora $FILELOCATION/Hub/.time-war/Theodora
    elif [[ $WAR_CHAR1 -eq 1 ]]; then
	mv $FILELOCATION/Hub/.time-war/.char-tim $FILELOCATION/Hub/.time-war/Tim
    elif [[ $WAR_CHAR1 -eq 2 ]]; then
	mv $FILELOCATION/Hub/.time-war/.char-robert $FILELOCATION/Hub/.time-war/Robert
    elif [[ $WAR_CHAR1 -eq 3 ]]; then
	mv $FILELOCATION/Hub/.time-war/.char-adam $FILELOCATION/Hub/.time-war/Adam
    else
	mv $FILELOCATION/Hub/.time-war/.char-mort $FILELOCATION/Hub/.time-war/Mort
    fi

    # Mad Max
    MAX_CHAR1=$(($RANDOM % $char_size))
    while [ $MAX_CHAR1 -eq ($HUB_CHAR1 || $HUB_CHAR2 || $MIDDLE_CHAR1 || $WAR_CHAR1) ]; do
	MAX_CHAR1=$(($RANDOM % $char_size))
    done
    if [[ $MAX_CHAR1 -eq 0 ]]; then
	mv $FILELOCATION/Hub/.time-max/.char-theodora $FILELOCATION/Hub/.time-max/Theodora
    elif [[ $MAX_CHAR1 -eq 1 ]]; then
	mv $FILELOCATION/Hub/.time-max/.char-tim $FILELOCATION/Hub/.time-max/Tim
    elif [[ $MAX_CHAR1 -eq 2 ]]; then
	mv $FILELOCATION/Hub/.time-max/.char-robert $FILELOCATION/Hub/.time-max/Robert
    elif [[ $MAX_CHAR1 -eq 3 ]]; then
	mv $FILELOCATION/Hub/.time-max/.char-adam $FILELOCATION/Hub/.time-max/Adam
    else
	mv $FILELOCATION/Hub/.time-max/.char-mort $FILELOCATION/Hub/.time-max/Mort
    fi
}

# Instructions
printf "You start in the Hub area, located in present day Lakeland. "
sleep 1
printf "Use the command "; tput bold; printf "ls "; tput sgr0; echo "to list useful locations or objects."
sleep 1
